# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build:
#     docker:
#       - image: mongo:4.2.0
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: cd backend && npm install && npm test
# workflows:
#     build-and-test:
#       jobs:
#         - build-and-test

version: 2.1
jobs:
  build:
    # working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: cd backend/ && npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
      - run:
          name: test
          command: cd backend/ && npm test
      # - run:
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      - store_test_results:
          path: test-results.xml