version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-npm-wee
          command: cd backend/ && npm install
      - run:
          name: test
          command: cd backend/ && npm test